version: '3.8'

services:
  cursor-api:
    image: hexsean/cursor2api:latest
    container_name: cursor-api
    restart: unless-stopped
    ports:
      - "13777:3000"
    volumes:
      - ./data:/app/data
    user: "1000:1000"